/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.brickinvestor;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Image;

/**
 *
 * @author davidpicariello
 */
public class CurrentInventoryJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CurrentInventoryJFrame
     */
    public CurrentInventoryJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.WARNING: Do NOT modify this code.The content of this method is always
 regenerated by the Form Editor.
     * @param inventory   
     */
    public static void setInventoryJTable(){
        //get instance of inventory
        Inventory inventory = Inventory.getInstance();
        ArrayList<Order> curInventory = inventory.getInventory();
        
        //set total amount invested
        jTextFieldTotalAmountInvested.setText(String.valueOf(inventory.getTotalAmountInvested()));
        //set total quantity
        jTextFieldTotalQuanity.setText(String.valueOf(inventory.getTotalQuantity()));
        //disable all the text boxes
        jTextFieldTotalAmountInvested.setEditable(false);
        jTextFieldTotalQuanity.setEditable(false);
        jTextNumberOfPieces.setEditable(false);
        jTextFieldYearOfRelease.setEditable(false);
        
        
        
        
        //create model
        DefaultTableModel model = (DefaultTableModel) tableInventory.getModel();
        //clear the inventory Jtable
        model.setRowCount(0);
        for (Order order:curInventory){
             AddRowToJTable(model,new Object[]{
                 order.getSetID(),
                 order.getDescription(),
                 order.getQuantity(),
                 "$"+order.getCostPerItem(),
                 "$"+order.getPricePerPiece(),
                 "$"+order.getTotalCost()});
        }
        
        
        
        
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableInventory = new javax.swing.JTable();
        jLabelDisplaySetImage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldYearOfRelease = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextNumberOfPieces = new javax.swing.JTextField();
        btnInfo = new javax.swing.JButton();
        jTextFieldTotalAmountInvested = new javax.swing.JTextField();
        jTextFieldTotalQuanity = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        tableInventory.setBackground(new java.awt.Color(255, 153, 153));
        tableInventory.setFont(new java.awt.Font("Optima", 1, 14)); // NOI18N
        tableInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Set Number", "Description", "Quanity", "Cost per Set", "Price per Piece", "Total Cost"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableInventory);
        if (tableInventory.getColumnModel().getColumnCount() > 0) {
            tableInventory.getColumnModel().getColumn(0).setResizable(false);
            tableInventory.getColumnModel().getColumn(1).setResizable(false);
            tableInventory.getColumnModel().getColumn(2).setResizable(false);
            tableInventory.getColumnModel().getColumn(3).setResizable(false);
            tableInventory.getColumnModel().getColumn(4).setResizable(false);
            tableInventory.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabelDisplaySetImage.setFont(new java.awt.Font("Optima", 1, 14)); // NOI18N
        jLabelDisplaySetImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lego.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Optima", 1, 18)); // NOI18N
        jLabel1.setText("Inventory");

        jLabel4.setFont(new java.awt.Font("Optima", 1, 14)); // NOI18N
        jLabel4.setText("Year of Release");

        jTextFieldYearOfRelease.setFont(new java.awt.Font("Optima", 1, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Optima", 1, 14)); // NOI18N
        jLabel5.setText("Number of Pieces");

        jTextNumberOfPieces.setFont(new java.awt.Font("Optima", 1, 14)); // NOI18N

        btnInfo.setBackground(new java.awt.Color(255, 153, 153));
        btnInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/info.png"))); // NOI18N
        btnInfo.setText("Info");
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        jTextFieldTotalAmountInvested.setFont(new java.awt.Font("Optima", 1, 14)); // NOI18N
        jTextFieldTotalAmountInvested.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalAmountInvestedActionPerformed(evt);
            }
        });

        jTextFieldTotalQuanity.setFont(new java.awt.Font("Optima", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Optima", 1, 14)); // NOI18N
        jLabel2.setText("Total Amount Invested");

        jLabel3.setFont(new java.awt.Font("Optima", 1, 14)); // NOI18N
        jLabel3.setText("Total Number Of Sets");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldYearOfRelease, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNumberOfPieces, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTotalAmountInvested, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTotalQuanity, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDisplaySetImage, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldYearOfRelease, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextNumberOfPieces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldTotalAmountInvested, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldTotalQuanity, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInfo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelDisplaySetImage, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTotalAmountInvestedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalAmountInvestedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalAmountInvestedActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed

        int selectedRow = tableInventory.getSelectedRow();
//         get instance of inventory
         Inventory inventory = Inventory.getInstance();

        if (selectedRow != -1) {
            //find order based off set ID and then pass info
            Object setID = tableInventory.getModel().getValueAt(selectedRow, 0);
            Order order = inventory.findOrder(setID);
             try {
                
                //resize image
                ImageIcon imgIcon = new ImageIcon(new URL(order.getUrl()));
                Image tmpImg  = imgIcon.getImage();
                
                // https://stackoverflow.com/questions/5895829/resizing-image-in-java
                Image newImage = tmpImg.getScaledInstance(420, 200, Image.SCALE_DEFAULT);
                jLabelDisplaySetImage.setIcon(new ImageIcon(newImage));
                //set numpirces and year release
                jTextNumberOfPieces.setText(String.valueOf(order.getNumPieces()));
                jTextFieldYearOfRelease.setText(order.getYearReleased());

                
                
             }catch (MalformedURLException ex) {
                Logger.getLogger(CurrentInventoryJFrame.class.getName()).log(Level.SEVERE, null, ex);
             }
        }else{
             JOptionPane.showMessageDialog(null, "Please select a row to get Info.");
        }
    }//GEN-LAST:event_btnInfoActionPerformed
    //Add Row to Table
       public static void AddRowToJTable(DefaultTableModel model,Object[] dataRow){
           
           model.addRow(dataRow);
       }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrentInventoryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrentInventoryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrentInventoryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrentInventoryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CurrentInventoryJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelDisplaySetImage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextField jTextFieldTotalAmountInvested;
    private static javax.swing.JTextField jTextFieldTotalQuanity;
    private static javax.swing.JTextField jTextFieldYearOfRelease;
    private static javax.swing.JTextField jTextNumberOfPieces;
    private static javax.swing.JTable tableInventory;
    // End of variables declaration//GEN-END:variables
}
