/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.brickinvestor;

/**
 *
 * @author davidpicariello
 */
public class HomeScreenWindow extends javax.swing.JFrame {

    /**
     * Creates new form HomeScreenWindow2
     */
    public HomeScreenWindow() {
        initComponents();
        
    }
    //Create Add order Jframe
    AddOrderJFrame AddOrder = new AddOrderJFrame();
    //Create Order Log Jframe
    OrderLogJFrame OrderLog = new OrderLogJFrame();
    //Create Current Inventory Jframe 
    CurrentInventoryJFrame CurrentInventory = new CurrentInventoryJFrame();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalesLog = new javax.swing.JButton();
        btnSupplies = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAddOrder = new javax.swing.JButton();
        btnAddSale = new javax.swing.JButton();
        btnCurrentInventory = new javax.swing.JButton();
        btnInventoryHistory = new javax.swing.JButton();
        btnOrderLog = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSalesLog.setText("Sales Log");
        btnSalesLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalesLogActionPerformed(evt);
            }
        });

        btnSupplies.setText("Supplies");
        btnSupplies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuppliesActionPerformed(evt);
            }
        });

        jLabel1.setText("BRICK INVESTOR");

        btnAddOrder.setText("Add Order");
        btnAddOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOrderActionPerformed(evt);
            }
        });

        btnAddSale.setText("Add Sale");

        btnCurrentInventory.setText("Current Inventory");
        btnCurrentInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCurrentInventoryActionPerformed(evt);
            }
        });

        btnInventoryHistory.setText("Inventory History");
        btnInventoryHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventoryHistoryActionPerformed(evt);
            }
        });

        btnOrderLog.setText("Order Log");
        btnOrderLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderLogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnOrderLog, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnInventoryHistory)
                                        .addComponent(btnCurrentInventory)))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSupplies)
                                    .addComponent(btnSalesLog))))
                        .addContainerGap(83, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(btnAddSale)
                        .addGap(87, 87, 87))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddOrder)
                    .addComponent(btnAddSale))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOrderLog)
                    .addComponent(btnSalesLog))
                .addGap(8, 8, 8)
                .addComponent(btnCurrentInventory)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnInventoryHistory))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnSupplies)))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalesLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalesLogActionPerformed

    private void btnSuppliesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuppliesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuppliesActionPerformed

    private void btnAddOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOrderActionPerformed
        // TODO add your handling code here:
        AddOrder.setVisible(true);
        
    }//GEN-LAST:event_btnAddOrderActionPerformed

    private void btnCurrentInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurrentInventoryActionPerformed
        // TODO add your handling code here:
        CurrentInventory.setVisible(true);
    }//GEN-LAST:event_btnCurrentInventoryActionPerformed

    private void btnInventoryHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryHistoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInventoryHistoryActionPerformed

    private void btnOrderLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderLogActionPerformed
        // TODO add your handling code here:
        OrderLog.setVisible(true);
    }//GEN-LAST:event_btnOrderLogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreenWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreenWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreenWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreenWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeScreenWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddOrder;
    private javax.swing.JButton btnAddSale;
    private javax.swing.JButton btnCurrentInventory;
    private javax.swing.JButton btnInventoryHistory;
    private javax.swing.JButton btnOrderLog;
    private javax.swing.JButton btnSalesLog;
    private javax.swing.JButton btnSupplies;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
