/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.brickinvestor;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author davidpicariello
 */
public class SalesLogJFrame extends javax.swing.JFrame {

    /**
     * Creates new form SalesLogJFrame
     */
    public SalesLogJFrame() {
        initComponents();
    }

    //Create Add Sale Jframe
    AddSaleJFrame AddSale = new AddSaleJFrame();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSaleLog = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnDeleteSale = new javax.swing.JButton();
        btnAddSale = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        tableSaleLog.setBackground(new java.awt.Color(153, 204, 255));
        tableSaleLog.setFont(new java.awt.Font("Optima", 1, 14)); // NOI18N
        tableSaleLog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order Number", "Quantity", "Order Total", "Description", "Net", "ROI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableSaleLog);
        if (tableSaleLog.getColumnModel().getColumnCount() > 0) {
            tableSaleLog.getColumnModel().getColumn(0).setResizable(false);
            tableSaleLog.getColumnModel().getColumn(1).setResizable(false);
            tableSaleLog.getColumnModel().getColumn(2).setResizable(false);
            tableSaleLog.getColumnModel().getColumn(3).setResizable(false);
            tableSaleLog.getColumnModel().getColumn(4).setResizable(false);
            tableSaleLog.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel3.setFont(new java.awt.Font("Optima", 1, 18)); // NOI18N
        jLabel3.setText("Sales Log");

        btnDeleteSale.setBackground(new java.awt.Color(153, 204, 255));
        btnDeleteSale.setFont(new java.awt.Font("Optima", 1, 14)); // NOI18N
        btnDeleteSale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteSale.setText("Delete");
        btnDeleteSale.setMaximumSize(new java.awt.Dimension(87, 25));
        btnDeleteSale.setMinimumSize(new java.awt.Dimension(87, 25));
        btnDeleteSale.setPreferredSize(new java.awt.Dimension(87, 25));
        btnDeleteSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSaleActionPerformed(evt);
            }
        });

        btnAddSale.setBackground(new java.awt.Color(153, 204, 255));
        btnAddSale.setFont(new java.awt.Font("Optima", 1, 14)); // NOI18N
        btnAddSale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddSale.setText("Add");
        btnAddSale.setMaximumSize(new java.awt.Dimension(87, 25));
        btnAddSale.setMinimumSize(new java.awt.Dimension(87, 25));
        btnAddSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSaleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeleteSale, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAddSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDeleteSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public static void setSaleLogJTable(){
        //get instance of inventory
        Inventory inventory = Inventory.getInstance();
        
        ArrayList<Sale> sales = inventory.getSales();
        
        //change room for description
        tableSaleLog.getColumnModel().getColumn(3).setPreferredWidth(200);
        tableSaleLog.getColumnModel().getColumn(1).setPreferredWidth(40);
        
        
        //create model
        DefaultTableModel model = (DefaultTableModel) tableSaleLog.getModel();
        //clear the Order Jtable
        model.setRowCount(0);
        for (Sale sale:sales){
             AddRowToJTable(model,new Object[]{sale.getOrderNumber(),
                sale.getQuantity(),
                "$"+sale.getOrderTotal(),
                sale.getDescription(),
                "$"+sale.getNet(),
                sale.getROI()});
        } 
    }
    
    
    private void btnAddSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSaleActionPerformed
        AddSale.setVisible(true);
    }//GEN-LAST:event_btnAddSaleActionPerformed

    private void btnDeleteSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSaleActionPerformed
        int selectedRow = tableSaleLog.getSelectedRow();
//         get instance of inventory
         Inventory inventory = Inventory.getInstance();

        if (selectedRow != -1) {
            DefaultTableModel model = (DefaultTableModel) tableSaleLog.getModel();
           // Get sales list
            ArrayList<Sale> sales = inventory.getSales();
             
            if (selectedRow < sales.size()) {
                // Remove the order from orders
                sales.remove(selectedRow);
                //set sales
                inventory.setSales(sales);
                // Update the orderlog table
                model.removeRow(selectedRow);
                //update inventory
                inventory.updateInventoryList();
                JOptionPane.showMessageDialog(null, "Sale removed successfully.");
            } else {
                JOptionPane.showMessageDialog(null, "Invalid selected row index.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row to clear.");
        }
            

    }//GEN-LAST:event_btnDeleteSaleActionPerformed
     //Add Row to Table
    public static void AddRowToJTable(DefaultTableModel model,Object[] dataRow){
           model.addRow(dataRow);
       }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesLogJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesLogJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesLogJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesLogJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesLogJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSale;
    private javax.swing.JButton btnDeleteSale;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable tableSaleLog;
    // End of variables declaration//GEN-END:variables
}
